services:
  - type: web
    name: social-workers-forum-api
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /api/schema/
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://social-workers-forum.netlify.app
      - key: SEED_DEMO
        value: "true"
      - key: POSTGRES_SSL
        value: "true"
      - key: DATABASE_URL
        sync: false