# Generated by Django 5.2.17 on 2026-09-05 14:49

import django.db.models.deletion
import website.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery/', validators=[website.validators.validate_image_upload])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('captured_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='events.event')),
            ],
            options={
                'ordering': ['-captured_at', '-created_at'],
            },
        ),
    ]
